### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by LeonardSSH** [LeonardSSH/vscord#31]
- [x] Setting to remove details/lower details stuff https://github.com/LeonardSSH/vscord/issues/30
- [x] ButtonEnabled disabled by default https://github.com/LeonardSSH/vscord/issues/28
- [x] Git branch support https://github.com/LeonardSSH/vscord/pull/35
- [ ] Support for Remote SSH & WSL https://github.com/LeonardSSH/vscord/issues/26

**Comment by hallainea** [comment]
thx you are the best
